### PR TITLE
ci: switch to go 1.17

### PR DESCRIPTION
**Pull request by RhinosF1**
Part of #26

### CODE REVIEW

**Comment by RhinosF1** [comment]
@Cian911

**Comment by RhinosF1** [comment]
I ran the tests via my fork and saw no issues

**Review by Cian911 — APPROVED** [review]
PR #27 has been approved by [GoMerge](https://github.com/Cian911/gomerge) tool. :rocket:

**Comment by Cian911** [comment]
Looks like there's some issue with the `setup-go` action for `1.18`. Just to be safe for the moment I think we can just upgrade to `1.17`

**Pull request merged**
